'use client';

import Navbar from './components/navbar/Navbar';
import ClientOnly from './components/ClientOnly';
import './globals.css'
import { Inter } from 'next/font/google'
import RegisterModal from './components/modals/RegisterModal';
import TosterProvider from './components/provider/TosterProvider';

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'hostshare',
  description: 'Generated by create next app',
}


export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ClientOnly>
          <TosterProvider/>
          <RegisterModal/>
          <Navbar/>
        </ClientOnly>
        {children}
      </body>
    </html>
  )
}
